#ifndef CONFIG_H
#define CONFIG_H

#define SERVER_PORT 2000

// Character
#define MOVE_SPEED 3
#define MAX_PLAYERS 2
#define MAX_HEALTH 100
#define CHARACTER_WIDTH 64
#define CHARACTER_HEIGHT 64
#define CHARACTER_HITBOX_WIDTH 20
#define CHARACTER_HITBOX_HEIGHT 20

// Bullet
#define MAX_BULLETS 3
#define BULLET_WIDTH 6
#define BULLET_HEIGHT 6
#define BULLET_DAMAGE 20
#define BULLET_SPEED 10.0f
#define BULLET_LIFETIME 1200

// Timing
#define FRAME_DELAY_MS 16
#define NETWORK_TICK_MS 16
#define CONNECTION_TIMEOUT_MS 10000
#define NETWORK_SEND_INTERVAL_MS 500

#endif